#!/bin/sh
# Begin /etc/init.d/fcron

### BEGIN INIT INFO
# Provides:            fcron
# Required-Start:      $local_fs 
# Should-Start:        $remote_fs $syslog
# Required-Stop:       $local_fs
# Should-Stop:         $remote_fs $syslog
# Default-Start:       3 4 5
# Default-Stop:        0 1 2 6
# Short-Description:   Starts fcron.
# Description:         Starts fcron daemon.
# X-LFS-Provided-By:   BLFS
### END INIT INFO

. /lib/lsb/init-functions

BIN_FILE="/usr/sbin/fcron"

#$LastChangedBy: bdubbs $
#$Date: 2011-12-05 20:37:16 -0600 (Mon, 05 Dec 2011) $

case "$1" in
   start)
      log_info_msg "Starting fcron..."
      start_daemon ${BIN_FILE}
      evaluate_retval
      ;;

   stop)
      log_info_msg "Stopping fcron..."
      killproc ${BIN_FILE}
      evaluate_retval
      ;;

   restart)
      $0 stop
      sleep 1
      $0 start
      ;;

   status)
      statusproc ${BIN_FILE}
      ;;

   *)
      echo "Usage: $0 {start|stop|restart|status}"
      exit 1
      ;;
esac

# End /etc/init.d/fcron
